/* Generated by Yosys 0.63 (git sha1 70a11c6bf0e8dd669f56c7da3587f78b405138e2, clang++ 17.0.0 -fPIC -O3) */

(* src = "fa.v:1.1-7.10" *)
module fa(a, b, c, sum, cout);
  (* src = "fa.v:2.11-2.12" *)
  input a;
  wire a;
  (* src = "fa.v:2.13-2.14" *)
  input b;
  wire b;
  (* src = "fa.v:2.15-2.16" *)
  input c;
  wire c;
  (* src = "fa.v:3.12-3.15" *)
  output sum;
  wire sum;
  (* src = "fa.v:3.16-3.20" *)
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  assign _0_ = ~(b ^ a);
  assign sum = ~(_0_ ^ c);
  assign _1_ = b & a;
  assign _2_ = c & ~(_0_);
  assign cout = _2_ | _1_;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "pm_para_as.v:2.1-28.10" *)
module p_as(a, b, cin, sum, cout);
  (* src = "pm_para_as.v:3.22-3.23" *)
  input [15:0] a;
  wire [15:0] a;
  (* src = "pm_para_as.v:3.24-3.25" *)
  input [15:0] b;
  wire [15:0] b;
  (* src = "pm_para_as.v:4.11-4.14" *)
  input cin;
  wire cin;
  (* src = "pm_para_as.v:5.24-5.27" *)
  output [15:0] sum;
  wire [15:0] sum;
  (* src = "pm_para_as.v:6.12-6.16" *)
  output cout;
  wire cout;
  (* src = "pm_para_as.v:12.17-12.26" *)
  wire [15:0] b_inverse;
  (* src = "pm_para_as.v:9.15-9.20" *)
  wire [16:0] carry;
  assign b_inverse[14] = cin ^ b[14];
  assign b_inverse[13] = b[13] ^ cin;
  assign b_inverse[12] = b[12] ^ cin;
  assign b_inverse[11] = b[11] ^ cin;
  assign b_inverse[10] = b[10] ^ cin;
  assign b_inverse[9] = b[9] ^ cin;
  assign b_inverse[8] = b[8] ^ cin;
  assign b_inverse[7] = b[7] ^ cin;
  assign b_inverse[6] = b[6] ^ cin;
  assign b_inverse[5] = b[5] ^ cin;
  assign b_inverse[4] = b[4] ^ cin;
  assign b_inverse[3] = b[3] ^ cin;
  assign b_inverse[2] = b[2] ^ cin;
  assign b_inverse[1] = b[1] ^ cin;
  assign b_inverse[0] = b[0] ^ cin;
  assign b_inverse[15] = b[15] ^ cin;
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[0].my_fa  (
    .a(a[0]),
    .b(b_inverse[0]),
    .c(cin),
    .cout(carry[1]),
    .sum(sum[0])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[10].my_fa  (
    .a(a[10]),
    .b(b_inverse[10]),
    .c(carry[10]),
    .cout(carry[11]),
    .sum(sum[10])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[11].my_fa  (
    .a(a[11]),
    .b(b_inverse[11]),
    .c(carry[11]),
    .cout(carry[12]),
    .sum(sum[11])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[12].my_fa  (
    .a(a[12]),
    .b(b_inverse[12]),
    .c(carry[12]),
    .cout(carry[13]),
    .sum(sum[12])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[13].my_fa  (
    .a(a[13]),
    .b(b_inverse[13]),
    .c(carry[13]),
    .cout(carry[14]),
    .sum(sum[13])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[14].my_fa  (
    .a(a[14]),
    .b(b_inverse[14]),
    .c(carry[14]),
    .cout(carry[15]),
    .sum(sum[14])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[15].my_fa  (
    .a(a[15]),
    .b(b_inverse[15]),
    .c(carry[15]),
    .cout(cout),
    .sum(sum[15])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[1].my_fa  (
    .a(a[1]),
    .b(b_inverse[1]),
    .c(carry[1]),
    .cout(carry[2]),
    .sum(sum[1])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[2].my_fa  (
    .a(a[2]),
    .b(b_inverse[2]),
    .c(carry[2]),
    .cout(carry[3]),
    .sum(sum[2])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[3].my_fa  (
    .a(a[3]),
    .b(b_inverse[3]),
    .c(carry[3]),
    .cout(carry[4]),
    .sum(sum[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[4].my_fa  (
    .a(a[4]),
    .b(b_inverse[4]),
    .c(carry[4]),
    .cout(carry[5]),
    .sum(sum[4])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[5].my_fa  (
    .a(a[5]),
    .b(b_inverse[5]),
    .c(carry[5]),
    .cout(carry[6]),
    .sum(sum[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[6].my_fa  (
    .a(a[6]),
    .b(b_inverse[6]),
    .c(carry[6]),
    .cout(carry[7]),
    .sum(sum[6])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[7].my_fa  (
    .a(a[7]),
    .b(b_inverse[7]),
    .c(carry[7]),
    .cout(carry[8]),
    .sum(sum[7])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[8].my_fa  (
    .a(a[8]),
    .b(b_inverse[8]),
    .c(carry[8]),
    .cout(carry[9]),
    .sum(sum[8])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "pm_para_as.v:18.12-24.10" *)
  fa \for_loop[9].my_fa  (
    .a(a[9]),
    .b(b_inverse[9]),
    .c(carry[9]),
    .cout(carry[10]),
    .sum(sum[9])
  );
  assign { carry[16], carry[0] } = { cout, cin };
endmodule
